CREATE TABLE code (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mark_code VARCHAR NOT NULL UNIQUE,
    product_GTIN VARCHAR NOT NULL,
    order_id BIGINT NOT NULL,
    order_uuid VARCHAR NOT NULL,
    sent_for_print BOOLEAN,
    sent_for_apply BOOLEAN,
    applied BOOLEAN,
    sale BOOLEAN
);
